### PR TITLE
Tionb public playlist page

### PR DESCRIPTION
**Pull request by Gnashed**
## Description

Wrote a promise to filter our returned data by isPublic being true.

Now rendering public playlists cards. Now using conditional rendering on playlist card just so we can share the same component on different pages with different UI elements.

Edit: Fourth commit resolves an issue that prevented the authenticated user from being able to edit/delete their playlist they set to public.

## Related Issue
#47 

## Motivation and Context

Public playlists should be a feature for all authenticated users.

## How Can This Be Tested?

Pull down and test before merging to main.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by MJSuttles — APPROVED** [review]
Works like a charm...

**Review by fmings — CHANGES_REQUESTED** [review]
Utilize current card component for public playlist page
Utilize eliminate any buttons not needed for public playlist

**Comment by Gnashed** [comment]
Now using conditional rendering on playlist card instead of creating another component. Thanks for the callout y'all!

**Review by Zpcolburn — APPROVED** [review]
👌

**Comment by Gnashed** [comment]
Fourth commit resolves an issue that prevented the authenticated user from being able to edit/delete their playlist they set to public.

**Review by fmings — APPROVED** [review]

**Pull request merged**
